easy_admin:
  site_name: 'Shopping Site'
  design:
    brand_color: '#1ABC9C'
    assets:
      css: ['css/custom_backend.css']

  list:
    title: 'List of %%entity_label%%'
    actions: ['show']
  entities:
    Product:
      class: AppBundle\Entity\Product
      label: Products
      help: '2 year warranty product'
      list:
        help: 'Warranty Product'
        actions: ['-show']
      disabled_actions: ['show']
      search:
        help: null


    Category:
      class: AppBundle\Entity\Category
      label: Categories

    User:
      class: AppBundle\Entity\User
      label: Users
      list:
        actions:
          - { name: edit, icon: pencil, label: Edit }
          - { name: show, icon: info-circle, label: Show }
        fields:
          - id
          - username
          - { property: email, type: email}
          - { property: Enabled, type: 'toggle', fieldType: 'checkbox', dataType: 'toggle' }
          - {property: lastlogin, type: 'datetime' , label: 'Last_login'}
        sort: ['username','ASC']
      search:
        fields: [id,username]
