<?php


namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 * @ORM\Table(name="`user`")
 */
class User extends BaseUser
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    protected $id;
    /**
     * @ORM\Column(type="string")
     */
    protected $firstName;

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * @param mixed $firstName
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    public function setEmail($email)
    {
        $this->setUsername($email);
        return parent::setEmail($email); // TODO: Change the autogenerated stub
    }

    public function isEnabled()
    {
        return parent::isEnabled(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    public function setEnabled($boolean)
    {
        return parent::setEnabled($boolean); // TODO: Change the autogenerated stub
    }



    public function feed($food)
    {
        $foodItems = [];
        foreach ($food as $foodItem) {
            $foodItems[] = $foodItem;
        }

        if (count($foodItems) == 0) {
            return sprintf('%s is looking at you', $this->getUsername());
        }
        return sprintf('%s recently ate: %s', $this->getUsername(), implode(', ', $foodItems));
    }
}